-- Generated by tools/build_zh_cn_font.py; do not edit by hand.
-- QuanPixel glyphs are copied at native resolution into 8x8 cells.
return {
  ["zh_cn_000"] = {
    image = "mods/zh_cn/lang/font/zh_cn_000.png",
    base = 0x100,
    glyphsPerRow = 16,
    advance = 8,
  },
  ["zh_cn_001"] = {
    image = "mods/zh_cn/lang/font/zh_cn_001.png",
    base = 0x200,
    glyphsPerRow = 16,
    advance = 8,
  },
  ["zh_cn_002"] = {
    image = "mods/zh_cn/lang/font/zh_cn_002.png",
    base = 0x300,
    glyphsPerRow = 16,
    advance = 8,
  },
  ["zh_cn_003"] = {
    image = "mods/zh_cn/lang/font/zh_cn_003.png",
    base = 0x400,
    glyphsPerRow = 16,
    advance = 8,
  },
  ["zh_cn_004"] = {
    image = "mods/zh_cn/lang/font/zh_cn_004.png",
    base = 0x500,
    glyphsPerRow = 16,
    advance = 8,
  },
  ["zh_cn_005"] = {
    image = "mods/zh_cn/lang/font/zh_cn_005.png",
    base = 0x600,
    glyphsPerRow = 16,
    advance = 8,
  },
  ["zh_cn_006"] = {
    image = "mods/zh_cn/lang/font/zh_cn_006.png",
    base = 0x700,
    glyphsPerRow = 16,
    advance = 8,
  },
  ["zh_cn_007"] = {
    image = "mods/zh_cn/lang/font/zh_cn_007.png",
    base = 0x800,
    glyphsPerRow = 16,
    advance = 8,
  },
}
